---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: sandstone
---

# Here are some plots
today we are making intactive plots in poltly! Make examples using NYC airbnb
```{r message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```
do some initial data cleaning
```{r message=FALSE}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |>
  mutate(
    rating=review_scores_location/2
  ) |>
  select(rating,neighbourhood_group,neighbourhood,
         room_type,lat,long,price)|>
  drop_na(rating) |>
  filter(
    neighbourhood_group=="Manhattan",
    room_type=="Entire home/apt",
    price %in% 100:500
  )
```
use plotly to make some quick plots.
scatter
```{r}
nyc_airbnb |>
  mutate(text_label=str_c("Price",price,
                          "\nNeighborhood",neighbourhood)) |>
  plot_ly(
    x =~lat, y=~long,color=~price,text=~text_label,
    type="scatter",mode="markers",alpha = 0.5
    
  )
```
boxplot
```{r}
nyc_airbnb |>
  mutate(neighbourhood=fct_reorder(neighbourhood,price)) |>
  plot_ly(
    x=~neighbourhood,y=~price,
    type = "box",
    color = ~neighbourhood,
    colors = "viridis"
  )
```





bar chart with number of rentals
```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood=fct_reorder(neighbourhood,n)) |>
  plot_ly(
    x=~neighbourhood,y=~n,
          type = "bar")
```
 
 
